name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install selenium gspread beautifulsoup4 gspread google-auth google-auth-oauthlib google-auth-httplib2 oauth2client
      
    - name: Install Chrome
      run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
          google-chrome --version

    - name: Install ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget -q -O chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chromedriver-linux64.zip
        # Check if the file was downloaded
        if [ ! -f chromedriver.zip ]; then
          echo "ChromeDriver download failed. Exiting."
          exit 1
        fi
          unzip chromedriver.zip
          # ls -R  # Debugging: List extracted files
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version
          
    - name: Set up Google Credentials
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > service_account.json

    - name: Run Python Script
      run: |
        python TV_Scrapping.py

