name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install selenium gspread beautifulsoup4 gspread google-auth google-auth-oauthlib google-auth-httplib2 oauth2client
    
        
    - name: Set up Google Credentials
      run: echo "$GOOGLE_CREDENTIALS" > service_account.json

    - name: Run Python Script
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service_account.json
        python TV_Scrapping.py

